title: 'Java().Head.Brain'
author: Viktor Gamov
local_tz: America/New York
interpolate: false
disqus: nextjavaheadbraincom
#disqus_generate_id: true
disqus_developer: false
base_url: http://localhost:4242

asciidoctor:
  :compact: true
  :eruby: erubis
  :attributes:
    idprefix: ''
    idseparator: '-'
    icons: 'font'
    sectanchors: ''
    linkattrs: ''

scss:
  :line_numbers: true
  :style: :expanded
# if no profile is specified, the first with a deploy config is selected
profiles:
  development:
    minify: false
    disqus_developer: true
    dev: true
    deploy:
      dummy:
  production:
    base_url: http://next.javaheadbrain.com
    disqus_developer: false
    google_analytics: UA-40354726-1
    compass_output_style: :compressed
    minify: true
    deploy:
      host: github_pages
      branch: master