= Ground-up Introduction To In-Memory Data
Viktor Gamov
2015-01-27 22:56
:imagesdir: ../images
:icons: font
:keywords: hazelcast, imdg
:toc:
ifndef::awestruct[]
:awestruct-layout: post
:awestruct-tags: [hazelcast, imdg]
:idprefix:
:idseparator: -
endif::awestruct[]

.TL;DR
NOTE: This April, http://codepalousa.com/blog/2015/code-palousa-2015-session-listing/[I'm going to deliver] half-day workshop «Ground-up Introduction To In-Memory Data» at http://codepalousa.com[Code PaLOUsa] conference in Louisville, KY. 

You're an architect or a developer with years of experience creating amazing applications, but you've just been assigned to a *gasp* low latency project! Because you're an expert, you're expected to master a new _In-Memory caching/data technology_ and be productive from *day 1*. You feel completely lost as you open the JAR files. Not only that, but you have to contend with new topologies and data stores like NoSQL or Hadoop. 

Trust me, it's not as bad as it appears and setting up in-memory data is NOT as hard as you think. This hands-on workshop will cover the things you need to know to be successful on your first low latency in-memory based project.

== Brief Agenda Of A Workshop

Here is a brief agenda of this 1/2 Day Session:

* The In-Memory landscape you need to know
* Four Distributed Data Topologies that work well
* Making In-Memory Reliable, Scalable and Durable
* When to go NoSQL or not
* Techniques for Really Big In-Memory Data
* https://www.youtube.com/watch?v=zBaKtAQqfMo[Enough talk] - *Hands-on workshop*: In-Memory Alive and You Did it.

== Intrigued ?

Make sure that you're following https://twitter.com/CodePaLOUsa[conference] and https://twitter.com/gamussa[me] on twitter for updates. http://codepalousa.com/plan/event-location/[See you in Louisville, KY!]
