= NYJavaSig, February 2017
Viktor Gamov
2017-02-02 20:02
:imagesdir: ../images
:icons:
:keywords:
:toc:
ifndef::awestruct[]
:awestruct-layout: post
:awestruct-tags: [java, stream-api, jug]
:idprefix:
:idseparator: -
endif::awestruct[]


== Riding the Distributed Java Streams

== Slides

.Speakerdeck
++++
<script async class="speakerdeck-embed" data-id="2a44c22661014ab18bde0171507b0200" data-ratio="1.77777777777778" src="//speakerdeck.com/assets/embed.js"></script>
++++

.Slideshare
++++
<iframe src="//www.slideshare.net/slideshow/embed_code/key/1MucyCaur6vT52?startSlide=2" width="510" height="420" frameborder="0" marginwidth="0" marginheight="0" scrolling="no" style="border:1px solid #CCC; border-width:1px; margin-bottom:5px; max-width: 100%;" allowfullscreen> </iframe> <div style="margin-bottom:5px"> <strong> <a href="//www.slideshare.net/VikGamov/nyjavasig-riding-the-distributed-streams-feb-2nd-2017" title="[NYJavaSig] Riding the Distributed Streams - Feb 2nd, 2017" target="_blank">[NYJavaSig] Riding the Distributed Streams - Feb 2nd, 2017</a> </strong> from <strong><a target="_blank" href="//www.slideshare.net/VikGamov">Viktor Gamov</a></strong> </div>
++++

=== Grab the code icon:code-fork[]

.You can find code sample is following GH repository
https://github.com/gAmUssA/jet-streams-presentation

Branch for this talk `NYJavaSig_Feb2017`

== Tweets icon:twitter[]

[role="text-center"]
++++
<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Large crowd building for <a href="https://twitter.com/gAmUssA">@gAmUssA</a> and distributed streams at <a href="https://twitter.com/hashtag/nyjavasig?src=hash">#nyjavasig</a> meeting. <a href="https://twitter.com/java">@java</a> <a href="https://t.co/9AzXZHjcL8">pic.twitter.com/9AzXZHjcL8</a></p>&mdash; Frank Greco (@frankgreco) <a href="https://twitter.com/frankgreco/status/827301892850122752">February 2, 2017</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Great presentation by <a href="https://twitter.com/gAmUssA">@gAmUssA</a> about streams and <a href="https://twitter.com/hazelcast">@hazelcast</a> <a href="https://t.co/5fERKGoQ1r">pic.twitter.com/5fERKGoQ1r</a></p>&mdash; Biren (@birendev) <a href="https://twitter.com/birendev/status/827315714033905664">February 3, 2017</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Let&#39;s look at the code! <a href="https://twitter.com/gAmUssA">@gAmUssA</a> on distributed streams at <a href="https://twitter.com/hashtag/NYJavaSIG?src=hash">#NYJavaSIG</a> mtg <a href="https://twitter.com/java">@java</a> <a href="https://t.co/Z8l8NxdZoR">pic.twitter.com/Z8l8NxdZoR</a></p>&mdash; Frank Greco (@frankgreco) <a href="https://twitter.com/frankgreco/status/827313334915624960">February 3, 2017</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Distributed Streams by <a href="https://twitter.com/gAmUssA">@gAmUssA</a> at <a href="https://twitter.com/hashtag/NYJavaSIG?src=hash">#NYJavaSIG</a>. Thanks <a href="https://twitter.com/frankgreco">@frankgreco</a> <a href="https://twitter.com/CreditSuisse">@CreditSuisse</a> <a href="https://t.co/KgpHmWSv5I">pic.twitter.com/KgpHmWSv5I</a></p>&mdash; Sai Sharan Donthi (@sai_donthi) <a href="https://twitter.com/sai_donthi/status/827315748037152768">February 3, 2017</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">A traditional tweet from the stage <a href="https://twitter.com/hashtag/nyjavasig?src=hash">#nyjavasig</a>! <br>I asked people say Java 😃<a href="https://twitter.com/hashtag/hazelcastjet?src=hash">#hazelcastjet</a> <a href="https://twitter.com/hashtag/h?src=hash">#h</a>… <a href="https://t.co/jE35I39XBx">https://t.co/jE35I39XBx</a> <a href="https://t.co/r2DtjCrijK">pic.twitter.com/r2DtjCrijK</a></p>&mdash; Viktor Gamov (@gAmUssA) <a href="https://twitter.com/gAmUssA/status/827298089643958273">February 2, 2017</a></blockquote> <script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>
++++

